# Generated by Django 5.2.17 on 2026-10-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('exam', 'Module Exam')], default='lesson', help_text='Regular lesson, or the full module exam for the course', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pass_score_percent',
            field=models.PositiveIntegerField(default=70, help_text="Score (%) needed to pass this item's quiz/exam, if it has one"),
        ),
    ]
