# Generated by Django 5.2.17 on 2026-10-05 08:21

from django.db import migrations, models


def emoji_to_icon_names(apps, schema_editor):
    """Rows saved with emoji icons (before icons became Bootstrap Icons names)
    fall back to a sensible default; `seed_data` restores the specific icons."""
    defaults = {"Tier": "cloud-fill", "Course": "box-seam-fill", "Badge": "mortarboard-fill"}
    for model_name, default in defaults.items():
        model = apps.get_model("courses", model_name)
        for obj in model.objects.all():
            if not obj.icon.replace("-", "").isalnum() or not obj.icon.isascii():
                obj.icon = default
                obj.save(update_fields=["icon"])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_seed_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='trophy-fill', help_text='Bootstrap Icons name', max_length=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.CharField(default='box-seam-fill', help_text='Bootstrap Icons name', max_length=40),
        ),
        migrations.AlterField(
            model_name='tier',
            name='icon',
            field=models.CharField(default='cloud-fill', help_text='Bootstrap Icons name, e.g. cloud-fill', max_length=40),
        ),
        migrations.RunPython(emoji_to_icon_names, migrations.RunPython.noop),
    ]
