# Generated by Django 5.2.17 on 2026-10-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_import_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncompletion',
            name='score_percent',
            field=models.PositiveIntegerField(blank=True, help_text='Quiz or exam score when the lesson was completed (blank if it has no quiz)', null=True),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson_type', 'exam')), fields=('course',), name='one_exam_per_course'),
        ),
    ]
