# Generated by Django 5.2.17 on 2026-10-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='summary_sw',
            field=models.CharField(blank=True, max_length=300, verbose_name='Summary (Kiswahili)'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_sw',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title (Kiswahili)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_sw',
            field=models.TextField(blank=True, help_text='Optional Swahili version of the HTML. Keep the same quiz questions in the same order, with the same data-correct numbers.', verbose_name='Content (Kiswahili)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='summary_sw',
            field=models.CharField(blank=True, max_length=300, verbose_name='Summary (Kiswahili)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_sw',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title (Kiswahili)'),
        ),
        migrations.AddField(
            model_name='tier',
            name='name_sw',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Kiswahili)'),
        ),
        migrations.AddField(
            model_name='tier',
            name='summary_sw',
            field=models.CharField(blank=True, max_length=300, verbose_name='Summary (Kiswahili)'),
        ),
    ]
