# Generated by Django 5.2.17 on 2026-10-07 07:22

import courses.video
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_swahili_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quiz_size',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 asks every question each time. If the lesson holds more questions than this number, each attempt asks a different random set of this size.', verbose_name='Questions per attempt'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Optional. Upload an MP4 or WebM video (up to 200 MB). Use this or a YouTube link, or both.', upload_to='lesson_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogv']), courses.video.validate_video_size], verbose_name='Video file'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional. Paste a YouTube link (watch, share or embed address). It is shown at the top of the lesson.', verbose_name='YouTube link'),
        ),
    ]
