# Generated by Django 5.2.17 on 2026-10-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. 79%', max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('where', models.CharField(choices=[('home', 'Home page'), ('about', 'About page')], default='home', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['where', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('teach', 'About: how we teach'), ('audience', "About: who it's for"), ('different', 'About: why we are different'), ('role', 'About: open roles'), ('theory', 'Impact: theory of change step'), ('writes', 'Contact: who usually writes to us')], max_length=12)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap Icons name, e.g. shield-check', max_length=40)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default="Kenya's first cloud-literacy programme for kids", max_length=150)),
                ('hero_title_start', models.CharField(default='Every Kenyan child,', max_length=100)),
                ('hero_title_accent', models.CharField(default='cloud-ready', help_text='Highlighted word(s)', max_length=60)),
                ('hero_title_end', models.CharField(default='by 2030.', max_length=60)),
                ('hero_lead', models.TextField(default="Cloud for Kids teaches children aged 7-17 how data, the internet, and the cloud actually work, through school clubs, after-school hubs, and holiday bootcamps aligned to Kenya's CBC/CBE curriculum.")),
                ('hero_note', models.CharField(blank=True, default='Foundational, Intermediate, Advanced: a 3-tier pathway from Grade 4 to Grade 12.', max_length=200)),
                ('gap_title', models.CharField(default="Kenya's digital economy is growing faster than its cloud skills", max_length=200)),
                ('why_now_title', models.CharField(default='Why now?', max_length=100)),
                ('why_now_text', models.TextField(default="AWS, Microsoft, Samsung and Konza Technopolis are already investing in Kenya's digital skills ecosystem. Cloud for Kids plugs school-age children directly into that pipeline.")),
                ('about_title', models.CharField(default="Building Kenya's next generation of cloud-ready digital innovators", max_length=200)),
                ('about_lead', models.TextField(default="Cloud for Kids is a cloud computing literacy programme for children aged 7 to 17, taught through school partnerships and after-school learning hubs and aligned to Kenya's CBC/CBE curriculum.")),
                ('story_title', models.CharField(default='Closing the skills gap at the source', max_length=200)),
                ('story_text', models.TextField(default='', help_text='Separate paragraphs with a blank line')),
                ('mission', models.TextField(default='')),
                ('vision', models.TextField(default='')),
                ('north_star', models.CharField(default='Every Kenyan child, cloud-ready by 2030.', max_length=200)),
                ('contact_email', models.EmailField(default='adelinemakokha@gmail.com', max_length=254)),
                ('footer_email', models.EmailField(blank=True, default='info@cloudforkids.co.ke', max_length=254)),
                ('website', models.CharField(blank=True, default='www.cloudforkids.co.ke', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(default='Kenya, starting with an urban and peri-urban pilot', max_length=200)),
                ('response_time', models.CharField(default='We aim to reply within 2 working days', max_length=150)),
                ('footer_tagline', models.CharField(default="Building Kenya's cloud-ready generation, one classroom, one hub, one child at a time.", max_length=250)),
                ('footer_copyright', models.CharField(default="Cloud for Kids. Building Kenya's Next Generation of Cloud-Ready Digital Innovators.", max_length=250)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
