# Generated by Django 5.2.17 on 2026-10-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_site_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='role',
            field=models.CharField(blank=True, help_text='How they support the programme, e.g. Cloud credits', max_length=100),
        ),
    ]
