# Generated by Django 5.2.17 on 2026-10-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partner_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(help_text='HTML. Use <h2>, <p>, <ul> and <li>.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
