# Generated by Django 5.2.17 on 2026-10-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_four_tier_wording'),
    ]

    operations = [
        migrations.CreateModel(
            name='UITranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.TextField(unique=True)),
                ('swahili', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UI translation',
                'ordering': ['english'],
            },
        ),
    ]
