# Generated by Django 5.2.17 on 2026-10-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seed_ui_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.SlugField(help_text='Where it is used, for example about-hero, contact, tier-explorer', unique=True)),
                ('image', models.ImageField(blank=True, help_text='Upload a photo, or paste an address below', null=True, upload_to='site/')),
                ('url', models.URLField(blank=True, help_text='Address of an image, for example from Unsplash', max_length=400)),
                ('alt', models.CharField(blank=True, help_text='Describe the photo for screen readers', max_length=200)),
                ('credit_name', models.CharField(blank=True, help_text='Photographer, shown as a small credit', max_length=100)),
                ('credit_url', models.URLField(blank=True, max_length=400)),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
    ]
