# Generated by Django 5.2.17 on 2026-10-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ages_9_to_17_and_illustrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='about_lead',
            field=models.TextField(default="Cloud for Kids is a cloud computing literacy programme for children aged 9 to 17, taught through school partnerships and after-school learning hubs and aligned to Kenya's CBC/CBE curriculum."),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_lead',
            field=models.TextField(default="Cloud for Kids teaches children aged 9-17 how data, the internet, and the cloud actually work, through school clubs, after-school hubs, and holiday bootcamps aligned to Kenya's CBC/CBE curriculum."),
        ),
    ]
