# Generated by Django 5.2.17 on 2026-10-05 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_codes(apps, schema_editor):
    from accounts.models import new_family_code
    Profile = apps.get_model("accounts", "LearnerProfile")
    used = set()
    for prof in Profile.objects.filter(family_code__isnull=True):
        code = new_family_code()
        while code in used:
            code = new_family_code()
        used.add(code)
        prof.family_code = code
        prof.save(update_fields=["family_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='family_code',
            field=models.CharField(blank=True, editable=False, help_text='Secret code the learner gives a parent so the parent can link to this account', max_length=8, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ParentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.RunPython(backfill_codes, migrations.RunPython.noop),
    ]
