# Generated by Django 5.2.17 on 2026-10-05 12:15

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_classrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Progress summaries and reminders by email'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text="Facilitators need an admin's approval before they can use classes"),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When they accepted the Terms and Privacy Policy', null=True),
        ),
        migrations.CreateModel(
            name='ParentalConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(blank=True, max_length=150)),
                ('parent_email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=accounts.models.new_consent_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for parent'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('method', models.CharField(choices=[('email', 'Parent approved by email link'), ('school', 'Added by a school or facilitator'), ('admin', 'Recorded by an admin')], default='email', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
