# Generated by Django 5.2.17 on 2026-10-07 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notifications_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='location',
            field=models.CharField(blank=True, help_text='Where the class meets, e.g. Computer lab, Room 4', max_length=150),
        ),
        migrations.AddField(
            model_name='classroom',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Optional link for online sessions (Google Meet, Zoom, Teams)'),
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='e.g. Intro to cloud storage. Leave blank to use the class name', max_length=150)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('location', models.CharField(blank=True, help_text='Leave blank to use the class venue', max_length=150)),
                ('meeting_link', models.URLField(blank=True, help_text='Leave blank to use the class link')),
                ('notes', models.CharField(blank=True, help_text='e.g. Bring your laptop', max_length=300)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.classroom')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
